### ISSUE TITLE
Cannot get shareable raw link without VPN 

### ISSUE THREAD

**Issue by manuel-castro** [seung-lab/neuroglancer#420]
When I am using Neuroglancer outside of the lab and without the use of the VPN, I cannot get the legacy style link. After hitting share I get a message "Posting state to dynamicannotationserver...". I shouldn't need to have access to the link shortening server to get the raw link.

Edit: It seems like after a minute, the request does time out and I can hit "cancel" to get the raw link. This is still a bug though because the time to wait is way too long and having to hit cancel to get a raw link is not intuitive.

**Comment by ogewan** [comment]
This should be resolved by #423 . Closing for now but reopen if it happens again.

**Comment by manuel-castro** [comment]
This is still not fixed unfortunately. If you test hitting the share button on a Neuroglancer link that points to a link shortening server that requires the use of a VPN, then the raw url request will still take minutes
